### ISSUE TITLE
Code Duplicated in Records for GetInRange method - Consider consolidating into parent class

### ISSUE THREAD

**Issue by Hatterini** [Hatterini/4h_app#16]
Currently, the record entry classes: ActivityRecordEntry, ExpenseRecordEntry, FeedRecordEntry, RidingRecordEntry, and StableRecordEntry, have almost identical methods (GetInRange). If anything ever changes about one of these methods, it will be inconsistent with the rest. I suggest consolidating all of these methods onto their parent class, RecordBookEntry, and doing some string manipulation to get the desired outcome.

**Comment by BrianRistau** [comment]
I'll work on refactoring this behavior as I revise the UX/UI.

**Comment by BrianRistau** [comment]
Updated in the latest commit and fully functional - will push soon!
